Doctrine cookbook
slimphp/Slim-Website pull request #261
Opened 2017-11-11 00:33 UTC by 1ma

A new cookbook entry describing how to integrate Doctrine into Slim.

2017-12-20 14:16 UTC, geggleto requested changes

2017-12-20 14:16 UTC, geggleto commented on docs/cookbook/database-doctrine.md
> +/** @var \Slim\Container $cnt */
should this not be `$container`

2017-12-20 14:17 UTC, geggleto commented on docs/cookbook/database-doctrine.md
> +To be able to automatically run database migrations, validate class annotations and so on you need to create the Doctrine CLI application.
The console should be placed in the root of the project in the `cli-config.php` file (as per standard doctrine)

2018-02-09 17:01 UTC, geggleto commented
I'll review this weekend

2018-04-15 14:03 UTC, closed without merging

2018-04-15 14:03 UTC, akrabat commented
Merged in https://github.com/slimphp/Slim-Website/commit/eb93493274d888447e5f3d18d4be41dc43699b6f

2018-04-15 14:04 UTC, akrabat commented
Thanks @1ma.