Update Guzzle PSR-7 instructions for Slim 4.9
slimphp/Slim-Website pull request #594
Opened 2021-10-18 23:39 UTC by sapphirecat

Removes the Guzzle HTTP Factory from the base requirements, as it is no longer needed with the latest Slim 4 version.

Adds instructions for a new package that supports Guzzle PSR-7 version 1 on Slim 4.9.

See https://github.com/slimphp/Slim/issues/3121

2021-10-19 15:37 UTC, l0gicgate requested changes

2021-10-19 15:37 UTC, l0gicgate commented on docs/v4/start/installation.md
> +composer require sapphirecat/slim4-http-interop-adapter
I think we should just say this instead:

### [Guzzle PSR-7](https://github.com/guzzle/psr7)

#### For usage with Guzzle PSR-7 v2.x
```bash
composer require guzzlehttp/psr7 "^2"
```

#### For usage with Guzzle PSR-7 v1.x
```bash
composer require guzzlehttp/psr7 "^1"
composer require sapphirecat/slim4-http-interop-adapter
```

2021-10-20 00:19 UTC, sapphirecat commented on docs/v4/start/installation.md
> +composer require sapphirecat/slim4-http-interop-adapter
Thanks for the suggestion; that seems much simpler. I have amended the commit.

2021-10-21 14:19 UTC, l0gicgate approved these changes

2021-10-21 14:19 UTC, merged